/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 42;
=======
const int buildversion = 45;
>>>>>>> 74f611d972a72c5f099152425669fe76c8819fe8
const char buildconfig[] = "PAGING";
